#### Taking a random sample

In [20]:
import numpy as np

In [18]:
import pandas as pd

In [9]:
x = np.arange(1,101,1)
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [10]:
y = np.array([79,92,3,37,48])
y

array([79, 92,  3, 37, 48])

In [11]:
x.mean()

50.5

In [12]:
y.mean()

51.8

In [15]:
x.std()

28.86607004772212

In [16]:
y.std()

31.53030288468539

## Day2


In [4]:
num = np.array([23,11,56,74,19,53,25])

### Mean

In [6]:
num.mean()

37.285714285714285

In [7]:
np.mean(num)

37.285714285714285

In [8]:
sum(num)/len(num)

37.285714285714285

### Median

In [13]:
np.sort(num)

array([11, 19, 23, 25, 53, 56, 74])

In [14]:
np.median(num)

25.0

In [15]:
x=np.arange(1,91)
np.mean(x)

45.5

In [16]:
np.median(x)

45.5

### Mode

In [22]:
gender = pd.Series(['M','M','F','F','M','F','M','M','F','M'])
gender.value_counts()

M    6
F    4
dtype: int64

In [23]:
gender.mode()

0    M
dtype: object

In [24]:
age=pd.Series([22,21,20,20,21,21,20,22,23,21,20])
age.value_counts()

21    4
20    4
22    2
23    1
dtype: int64

In [25]:
age.mode()

0    20
1    21
dtype: int64

In [26]:
age.median()

21.0

In [27]:
age.mean()

21.0

### Mid-range

In [29]:
(num.max()+num.min())/2

42.5

### Mean absolute deviation

In [31]:
sum(abs(num - np.mean(num)))/len(num)

20.3265306122449

In [32]:
x = np.ones(10)+20
x

array([21., 21., 21., 21., 21., 21., 21., 21., 21., 21.])

In [33]:
sum(abs(x-np.mean(x)))/len(x)

0.0

### Variance

In [35]:
np.mean((num-np.mean(num))**2)

475.06122448979596

### Standard Deviation(SD)

In [37]:
np.sqrt(np.mean((num-np.mean(num))**2))

21.79589925857146

In [38]:
np.std(num)

21.79589925857146